### ISSUE TITLE
 Cannot invoke "java.util.Map.containsKey(Object)" because "this.mapResultLemmatization" is null

### ISSUE THREAD

**Issue by tarek-kerbedj** [seinecle/cowo-function#1]
I'm getting this Exception while trying to run the main code of  CowoFunction.java locally
I have tried with multiple text files to test and it seems like this error is persistent regardless of the input ( i have not changed the other parameters)

this happens in this step : 
finished 💇 entering lemmatization. [Duration: 8 milliseconds]
💇 finishing up lemmatization...

Error message: 
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "java.util.Map.containsKey(Object)" because "this.mapResultLemmatization" is null
	at net.clementlevallois.cowo.controller.CowoFunction.analyze(CowoFunction.java:395)
	at net.clementlevallois.cowo.controller.CowoFunction.main(CowoFunction.java:100)

**Comment by tarek-kerbedj** [comment]
okay after taking a deeper look, one of the language parameters was set to a language that was not English nor French but rather "pt"
Given that the code is monolithic, it was a bit difficult to track things

**Comment by seinecle** [comment]
Yes indeed this function is the longest, most complex one. I couldn't break it down in smaller parts, which makes it hard to understand and frankly, quite a pain to maintain as well.
